In [7]:
import numpy as np
import pandas as pd

#dataset with Disney movies and total_gross
disney_df = pd.read_csv('https://query.data.world/s/mkfcxqicohry4awyjy22wa6r3qg233?dws=00000')

disney_df

#Question to solve for: Does the popularity of a Disney movie correlate with the creation of a lego set?

,movie_title,release_date,genre,MPAA_rating,total_gross,inflation_adjusted_gross
0,Snow White and the Seven Dwarfs,"Dec 21, 1937",Musical,G,"$184,925,485","$5,228,953,251"
1,Pinocchio,"Feb 9, 1940",Adventure,G,"$84,300,000","$2,188,229,052"
2,Fantasia,"Nov 13, 1940",Musical,G,"$83,320,000","$2,187,090,808"
3,Song of the South,"Nov 12, 1946",Adventure,G,"$65,000,000","$1,078,510,579"
4,Cinderella,"Feb 15, 1950",Drama,G,"$85,000,000","$920,608,730"
...,...,...,...,...,...,...
574,The Light Between Oceans,"Sep 2, 2016",Drama,PG-13,"$12,545,979","$12,545,979"
575,Queen of Katwe,"Sep 23, 2016",Drama,PG,"$8,874,389","$8,874,389"
576,Doctor Strange,"Nov 4, 2016",Adventure,PG-13,"$232,532,923","$232,532,923"
577,Moana,"Nov 23, 2016",Adventure,PG,"$246,082,029","$246,082,029"
578,Rogue One: A Star Wars Story,"Dec 16, 2016",Adventure,PG-13,"$529,483,936","$529,483,936"

In [69]:
disney_df.genre = disney_df['genre'].apply(lambda x: 'Comedy' if x in ['Romantic Comedy', 'Black Comedy'] else 'Thriller' if x in ['Thriller/Suspense', 'Horror'] else 'Musical' if x in ['Concert/Performance'] else x)

In [52]:
# Local file path to the downloaded CSV file

file_path = '/Users/medirose/Downloads/lego_sets.csv'
# Read the CSV file into a DataFrame

legos_df = pd.read_csv(file_path)

legos_df

,ages,list_price,num_reviews,piece_count,play_star_rating,prod_desc,prod_id,prod_long_desc,review_difficulty,set_name,star_rating,theme_name,val_star_rating,country
0,6-12,29.9900,2.0,277.0,4.0,Catapult into action and take back the eggs fr...,75823.0,Use the staircase catapult to launch Red into ...,Average,Bird Island Egg Heist,4.5,Angry Birds™,4.0,US
1,6-12,19.9900,2.0,168.0,4.0,Launch a flying attack and rescue the eggs fro...,75822.0,Pilot Pig has taken off from Bird Island with ...,Easy,Piggy Plane Attack,5.0,Angry Birds™,4.0,US
2,6-12,12.9900,11.0,74.0,4.3,Chase the piggy with lightning-fast Chuck and ...,75821.0,Pitch speedy bird Chuck against the Piggy Car....,Easy,Piggy Car Escape,4.3,Angry Birds™,4.1,US
3,12+,99.9900,23.0,1032.0,3.6,Explore the architecture of the United States ...,21030.0,Discover the architectural secrets of the icon...,Average,United States Capitol Building,4.6,Architecture,4.3,US
4,12+,79.9900,14.0,744.0,3.2,Recreate the Solomon R. Guggenheim Museum® wit...,21035.0,Discover the architectural secrets of Frank Ll...,Challenging,Solomon R. Guggenheim Museum®,4.6,Architecture,4.1,US
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12256,7-14,36.5878,6.0,341.0,4.4,Protect NINJAGO® City from flying Manta Ray Bo...,70609.0,Help Cole save Shen-Li in this cool THE LEGO® ...,Easy,Manta Ray Bomber,4.3,THE LEGO® NINJAGO® MOVIE™,4.2,PT
12257,7-14,24.3878,8.0,217.0,4.1,Stop a Piranha Attack with Kai and Misako!,70629.0,Play out an action-packed Piranha Mech pursuit...,Easy,Piranha Attack,3.6,THE LEGO® NINJAGO® MOVIE™,4.1,PT
12258,7-14,24.3878,18.0,233.0,4.6,Stop a crime in the NINJAGO® City street market!,70607.0,"Team up with Lloyd Garmadon, Nya and Officer T...",Easy,NINJAGO® City Chase,4.6,THE LEGO® NINJAGO® MOVIE™,4.5,PT
12259,6-14,12.1878,1.0,48.0,5.0,Achieve Spinjitzu greatness with the Green Ninja!,70628.0,Learn all the skills of Spinjitzu with THE LEG...,Very Easy,Lloyd - Spinjitzu Master,5.0,THE LEGO® NINJAGO® MOVIE™,5.0,PT
12260,6-14,12.1878,11.0,109.0,4.5,Practice your Spinjitzu skills with Kai and Zane!,70606.0,Join the ninja heroes at the dojo with this ac...,Easy,Spinjitzu Training,4.7,THE LEGO® NINJAGO® MOVIE™,4.8,PT

In [53]:
legos_df.drop(columns=['ages', 'num_reviews', 'play_star_rating', 'prod_desc', 'val_star_rating'], inplace=True)

legos_df

,list_price,piece_count,prod_id,prod_long_desc,review_difficulty,set_name,star_rating,theme_name,country
0,29.9900,277.0,75823.0,Use the staircase catapult to launch Red into ...,Average,Bird Island Egg Heist,4.5,Angry Birds™,US
1,19.9900,168.0,75822.0,Pilot Pig has taken off from Bird Island with ...,Easy,Piggy Plane Attack,5.0,Angry Birds™,US
2,12.9900,74.0,75821.0,Pitch speedy bird Chuck against the Piggy Car....,Easy,Piggy Car Escape,4.3,Angry Birds™,US
3,99.9900,1032.0,21030.0,Discover the architectural secrets of the icon...,Average,United States Capitol Building,4.6,Architecture,US
4,79.9900,744.0,21035.0,Discover the architectural secrets of Frank Ll...,Challenging,Solomon R. Guggenheim Museum®,4.6,Architecture,US
...,...,...,...,...,...,...,...,...,...
12256,36.5878,341.0,70609.0,Help Cole save Shen-Li in this cool THE LEGO® ...,Easy,Manta Ray Bomber,4.3,THE LEGO® NINJAGO® MOVIE™,PT
12257,24.3878,217.0,70629.0,Play out an action-packed Piranha Mech pursuit...,Easy,Piranha Attack,3.6,THE LEGO® NINJAGO® MOVIE™,PT
12258,24.3878,233.0,70607.0,"Team up with Lloyd Garmadon, Nya and Officer T...",Easy,NINJAGO® City Chase,4.6,THE LEGO® NINJAGO® MOVIE™,PT
12259,12.1878,48.0,70628.0,Learn all the skills of Spinjitzu with THE LEG...,Very Easy,Lloyd - Spinjitzu Master,5.0,THE LEGO® NINJAGO® MOVIE™,PT
12260,12.1878,109.0,70606.0,Join the ninja heroes at the dojo with this ac...,Easy,Spinjitzu Training,4.7,THE LEGO® NINJAGO® MOVIE™,PT

In [54]:
legos_df.review_difficulty = legos_df['review_difficulty'].apply(lambda x: 'Easy' if x in ['Very Easy'] else ('Challenging' if x in ['Very Challenging'] else x))

In [55]:
legos_df['list_price'] = legos_df['list_price'].round(2)

legos_df

,list_price,piece_count,prod_id,prod_long_desc,review_difficulty,set_name,star_rating,theme_name,country
0,29.99,277.0,75823.0,Use the staircase catapult to launch Red into ...,Average,Bird Island Egg Heist,4.5,Angry Birds™,US
1,19.99,168.0,75822.0,Pilot Pig has taken off from Bird Island with ...,Easy,Piggy Plane Attack,5.0,Angry Birds™,US
2,12.99,74.0,75821.0,Pitch speedy bird Chuck against the Piggy Car....,Easy,Piggy Car Escape,4.3,Angry Birds™,US
3,99.99,1032.0,21030.0,Discover the architectural secrets of the icon...,Average,United States Capitol Building,4.6,Architecture,US
4,79.99,744.0,21035.0,Discover the architectural secrets of Frank Ll...,Challenging,Solomon R. Guggenheim Museum®,4.6,Architecture,US
...,...,...,...,...,...,...,...,...,...
12256,36.59,341.0,70609.0,Help Cole save Shen-Li in this cool THE LEGO® ...,Easy,Manta Ray Bomber,4.3,THE LEGO® NINJAGO® MOVIE™,PT
12257,24.39,217.0,70629.0,Play out an action-packed Piranha Mech pursuit...,Easy,Piranha Attack,3.6,THE LEGO® NINJAGO® MOVIE™,PT
12258,24.39,233.0,70607.0,"Team up with Lloyd Garmadon, Nya and Officer T...",Easy,NINJAGO® City Chase,4.6,THE LEGO® NINJAGO® MOVIE™,PT
12259,12.19,48.0,70628.0,Learn all the skills of Spinjitzu with THE LEG...,Easy,Lloyd - Spinjitzu Master,5.0,THE LEGO® NINJAGO® MOVIE™,PT
12260,12.19,109.0,70606.0,Join the ninja heroes at the dojo with this ac...,Easy,Spinjitzu Training,4.7,THE LEGO® NINJAGO® MOVIE™,PT

In [56]:
legos_df.theme_name.value_counts()

theme_name
Star Wars™                               1377
DUPLO®                                   1166
City                                     1092
Juniors                                   978
THE LEGO® NINJAGO® MOVIE™                 796
BrickHeadz                                765
Friends                                   606
THE LEGO® BATMAN MOVIE                    533
Technic                                   505
Marvel Super Heroes                       414
Creator 3-in-1                            403
Classic                                   332
Creator Expert                            317
Minecraft™                                303
Disney™                                   285
DIMENSIONS™                               280
MINDSTORMS®                               272
NINJAGO®                                  263
Speed Champions                           254
Architecture                              210
NEXO KNIGHTS™                             197
Elves                                     195
DC Comics™ Super Heroes                   148
Ideas                                     128
SERIOUS PLAY®                              84
Minifigures                                70
DC Super Hero Girls                        32
Ghostbusters™                              23
Carnotaurus Gyrosphere Escape              21
Pteranodon Chase                           21
Stygimoloch Breakout                       21
Blue's Helicopter Pursuit                  21
Dilophosaurus Outpost Attack               21
Jurassic Park Velociraptor Chase           21
T. rex Transport                           21
Power Functions                            21
Indoraptor Rampage at Lockwood Estate      21
BOOST                                      19
LEGO® Creator 3-in-1                       16
Angry Birds™                                6
Name: count, dtype: int64

In [66]:
mask = legos_df['prod_long_desc'].str.contains('Disney', case=False)

disneylegos_df = legos_df[mask]

disneylegos_df

,list_price,piece_count,prod_id,prod_long_desc,review_difficulty,set_name,star_rating,theme_name,country
16,19.99,160.0,41613.0,These LEGO® BrickHeadz™ 41613 Mr. Incredible &...,Easy,Mr. Incredible & Frozone,5.0,BrickHeadz,US
36,9.99,118.0,41594.0,"New for March 2017, LEGO® BrickHeadz construct...",Easy,Captain Armando Salazar,5.0,BrickHeadz,US
40,9.99,109.0,41593.0,"New for March 2017, LEGO® BrickHeadz construct...",Easy,Captain Jack Sparrow,4.8,BrickHeadz,US
42,9.99,139.0,41595.0,"New for March 2017, LEGO® BrickHeadz construct...",Easy,Belle,4.8,BrickHeadz,US
43,9.99,116.0,41596.0,"New for March 2017, LEGO® BrickHeadz construct...",Average,Beast,5.0,BrickHeadz,US
...,...,...,...,...,...,...,...,...,...
12000,18.29,67.0,10738.0,Stop by for a visit at Disney Snow White’s For...,Average,Snow White's Forest Cottage,5.0,Juniors,PT
12002,12.19,47.0,10730.0,Join in the exciting Disney•Pixar Cars 3 racin...,Easy,Lightning McQueen Speed Launcher,4.0,Juniors,PT
12003,12.19,62.0,10733.0,Join Mater in his Easy to Build junkyard as he...,Easy,Mater's Junkyard,4.7,Juniors,PT
12004,12.19,75.0,10732.0,Join in the Disney•Pixar Cars 3 fun at Guido &...,NaN,Guido and Luigi's Pit Stop,5.0,Juniors,PT
12005,12.19,59.0,10731.0,Be part of the exciting Disney•Pixar Cars 3 ra...,Easy,Cruz Ramirez Race Simulator,5.0,Juniors,PT